### ISSUE TITLE
Slow down ADC clock speed and allow longer RTT

### ISSUE THREAD

**Issue by hartytp** [m-labs/nu-servo#3]
As I understand it, currently with the ADC running at 125MHz DDR
- t_adc=82 
- t_iir = 49 
- t_dds=146 
- t_dds = t_adc+t_iir then max t_rtt is 19 (152ns)
- The ADC specifies a max clk -> clkout delay of 4ns, but let's give it 8. That leaves 18 clock cycles free for RTT.
- Let's assume we need a max cable length of 10m. RTT is < 66ns=8 clock cycles (assume 1ft/ns).
- That means we currently have 11 clock cycles spare even with long cables.

1. Provisionally, it seems that 125MHz DDR can be supported over 10m SCSI cables. So, the current timing should be fine. However, I wonder if it would be more robust (and potentially save us some hassle later on) to run the ADC in SDR mode. That only costs us 5 additional clock cycles = 40ns, which is pretty negligible on a 1.1us cycle time.
2. I'd really like it if we could change the sequencing to allow t_adc+t_iir+t_rrt > t_dds for remote EEMs.

**Comment by jordens** [comment]
https://github.com/m-labs/artiq/commit/b44d6517d1cbf960804c0c5c3c9f8bdf2a20d484
