### ISSUE TITLE
ADC/IIR max/min values

### ISSUE THREAD

**Issue by hartytp** [m-labs/nu-servo#4]
We need a means of checking whether any servo channel/profile has railed, and also of logging the IIR input/outputs over time (e.g. to watch for head room slowly decreasing due to fibre coupling efficiency degrading over time or whatever).

The way I'd imagine doing this (comments welcome) is:
- for each channel/profile, we store the max/min IIR input (ADC value) and output (DDS ASD). These should clear on read, so that each read gives the max/min value since the last read. These max/min values should only update when the servo is running (integrator active). I think we previously discussed having just a "railed" indicator, but on reflection, max/min values would be nicer. 
- one schedules an experiment to run every 10s of seconds to minutes, which reads the max/min value for each profile one cares about and broadcasts them.
- a GUI/log can then pick these up and do something with them

**Comment by jordens** [comment]
Please remove this to artiq. This repo is just legacy code.and won't evolve.
